name: easy_extension
description: Useful Extensions for Flutter.
version: 0.0.7
homepage: https://github.com/scadasystems
repository: https://github.com/scadasystems/Easy-Extension

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.3
  collection:
  encrypt: ^5.0.1
  gap: ^3.0.1
  intl:
  meta: ^1.10.0
  pigment: ^1.0.4
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
